services:
  frontend:
    build:
      context: ./frontend
      target: production
    restart: always

  backend:
    build:
      context: ./backend
      target: production
    volumes:
      - backend_public:/var/www/html/public
    restart: always

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - backend_public:/var/www/html/public
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  backend_public:
